export const DATA_SOURCES = {
  airtable:
    "https://airtable.com/appK49oThZBOTSYlX/shr5Chudz00G5jxwW/tblFlqQHeAvsVxLNI",
  felt: "https://felt.com/map/LUX-NYC-tki3mxiaS9B2Uc9Bg3EN9BWJB",
};

export const AREAS = [
  {
    id: "all",
    number: "01",
    label: "The Whole Board",
    shortLabel: "Whole Board",
    focus: { lat: 40.7278, lng: -73.9955, distance: 88, height: 62, rotation: 0.64 },
    description:
      "47 AI companies across six startup clusters. Frontier labs, creative tools, infrastructure, fintech, and health, mapped block by block across Manhattan and Brooklyn.",
  },
  {
    id: "midtown",
    number: "02",
    label: "Midtown Stack",
    shortLabel: "Midtown",
    focus: { lat: 40.7504, lng: -73.9847, distance: 36, height: 31, rotation: 0.36 },
    description:
      "The heavyweight corridor. Infrastructure and media names (voice AI, data platforms, dev tooling) anchored to the Grand Central transit spine.",
  },
  {
    id: "flatiron",
    number: "03",
    label: "Flatiron / Union Square",
    shortLabel: "Flatiron",
    focus: { lat: 40.7352, lng: -73.9902, distance: 30, height: 26, rotation: 0.44 },
    description:
      "The densest few blocks on the map. Dozens of early-stage teams building creative AI, automation, and developer tools, packed within a short walk of Union Square.",
  },
  {
    id: "west-side",
    number: "04",
    label: "West Side / Chelsea",
    shortLabel: "West Side",
    focus: { lat: 40.7393, lng: -74.0069, distance: 32, height: 26, rotation: 0.74 },
    description:
      "The Hudson edge, where frontier labs and late-stage operators share the waterfront with Chelsea's big-tech offices.",
  },
  {
    id: "soho",
    number: "05",
    label: "SoHo / NoHo",
    shortLabel: "SoHo",
    focus: { lat: 40.7216, lng: -74.001, distance: 28, height: 24, rotation: 0.82 },
    description:
      "A compact downtown pocket of applied-AI products and model infrastructure, tucked among the cast-iron lofts.",
  },
  {
    id: "fidi",
    number: "06",
    label: "Tribeca / FiDi",
    shortLabel: "FiDi",
    focus: { lat: 40.7071, lng: -74.0097, distance: 34, height: 27, rotation: 0.9 },
    description:
      "Lower Manhattan skews legal, financial, and industrial: regulated-world AI built in the shadow of Wall Street.",
  },
  {
    id: "brooklyn",
    number: "07",
    label: "Brooklyn Arc",
    shortLabel: "Brooklyn",
    focus: { lat: 40.6995, lng: -73.982, distance: 46, height: 28, rotation: 1.18 },
    description:
      "Across the East River through DUMBO, Williamsburg, and the Navy Yard: open-source, hardware, and marketplace teams with room to build.",
  },
];

// Optional per-startup enrichment fields the company card renders when
// present: founded (year), team (approx headcount), raised (latest round).
// Only add values verified against an authoritative source.
export const STARTUPS = [
  { id: "65a0d5fc", name: "Abnormal Security", lat: 40.7349661, lng: -73.9905946, area: "flatiron", stage: null, sector: "Mapped startup", office: null, website: null, source: "felt" },
  { id: "d5a8e3da", name: "Adonis", lat: 40.7058848, lng: -74.0091414, area: "fidi", stage: null, sector: "Mapped startup", office: null, website: null, source: "felt" },
  { id: "alphasense", name: "AlphaSense", lat: 40.7538005, lng: -73.9962297, area: "west-side", stage: "Late-Stage", sector: "Financial Services", office: "HQ", website: "https://www.alpha-sense.com/", source: "company", address: "441 Ninth Avenue, New York, NY 10001" },
  { id: "01d9c120", name: "Arena AI", lat: 40.7349396, lng: -73.9885798, area: "flatiron", stage: "Early-Stage", sector: "Enterprise Automation", office: "HQ", website: "https://www.arena-ai.com/", source: "felt+airtable" },
  { id: "24a8d04f", name: "Axion Ray", lat: 40.7156999, lng: -73.963491, area: "brooklyn", stage: "Early-Stage", sector: "Manufacturing & Industrials", office: "HQ", website: "https://www.axionray.com/", source: "felt+airtable" },
  { id: "02910734", name: "Basis", lat: 40.7377422, lng: -73.9908636, area: "flatiron", stage: "Early-Stage", sector: "Financial Services", office: "HQ", website: "https://www.getbasis.ai/", source: "felt+airtable" },
  { id: "55265691", name: "Captions", lat: 40.7317604, lng: -73.9932236, area: "flatiron", stage: "Early-Stage", sector: "Media/Creative", office: "HQ", website: "https://www.captions.ai/", source: "felt+airtable" },
  { id: "aea536d9", name: "Character.ai", lat: 40.7306952, lng: -73.9892212, area: "flatiron", stage: "Late-Stage", sector: "Media/Creative", office: "Satellite Office", website: "https://character.ai/", source: "felt+airtable" },
  { id: "df0ea37f", name: "Cognition", lat: 40.7319764, lng: -73.9865154, area: "flatiron", stage: "Early-Stage", sector: "Coding", office: "Satellite Office", website: "https://www.cognition-labs.com/", source: "felt+airtable" },
  { id: "69020f2f", name: "Cohere", lat: 40.7366681, lng: -74.0072847, area: "west-side", stage: "Late-Stage", sector: "AI/Data Infrastructure", office: "Satellite Office", website: "https://cohere.com/", source: "felt+airtable" },
  { id: "7b24b80e", name: "Conductor AI", lat: 40.7063507, lng: -74.0071942, area: "fidi", stage: "Early-Stage", sector: "Manufacturing & Industrials", office: "HQ", website: "https://www.conductorai.co/", source: "felt+airtable" },
  { id: "crosby", name: "Crosby", lat: 40.7221, lng: -73.9971, area: "soho", stage: "Early-Stage", sector: "Legal", office: "HQ", website: "https://crosby.ai/", source: "user" },
  { id: "dataiku", name: "Dataiku", lat: 40.7393401, lng: -73.9893929, area: "flatiron", stage: "Late-Stage", sector: "AI/Data Infrastructure", office: "HQ", website: "https://www.dataiku.com/", source: "company", address: "902 Broadway, New York, NY 10010" },
  { id: "dataminr", name: "Dataminr", lat: 40.7467776, lng: -73.9848139, area: "midtown", stage: "Late-Stage", sector: "AI Application", office: "HQ", website: "https://www.dataminr.com/", source: "company", address: "6 East 32nd Street, New York, NY 10016" },
  { id: "f0167ce8", name: "Diode", lat: 40.698723, lng: -73.9760711, area: "brooklyn", stage: "Early-Stage", sector: "Manufacturing & Industrials", office: "HQ", website: "https://diode.computer/", source: "felt+airtable" },
  { id: "ea7b3bc6", name: "Diplo AI", lat: 40.7076981, lng: -74.0083393, area: "fidi", stage: null, sector: "Mapped startup", office: null, website: null, source: "felt" },
  { id: "4c1746d2", name: "Eleven Labs", lat: 40.7473539, lng: -73.9829156, area: "midtown", stage: "Late-Stage", sector: "Media/Creative", office: "Satellite Office", website: "https://elevenlabs.io/", source: "felt+airtable" },
  { id: "eliseai", name: "EliseAI", lat: 40.7499362, lng: -73.9832705, area: "midtown", stage: "Late-Stage", sector: "Enterprise Automation", office: "HQ", website: "https://eliseai.com/", source: "company", address: "401 Fifth Avenue, New York, NY 10016" },
  { id: "a7dc7d0e", name: "Endex", lat: 40.7253805, lng: -74.0010235, area: "west-side", stage: "Early-Stage", sector: "Financial Services", office: "HQ", website: "https://endex.ai/", source: "felt+airtable" },
  { id: "4fcaccfb", name: "Glif.app", lat: 40.7522186, lng: -73.9772717, area: "midtown", stage: "Early-Stage", sector: "Media/Creative", office: "HQ", website: "https://glif.app/glifs", source: "felt+airtable" },
  { id: "3789f8f2", name: "Hebbia", lat: 40.7207237, lng: -74.0010337, area: "soho", stage: "Early-Stage", sector: "Enterprise Automation", office: "HQ", website: "https://www.hebbia.ai/", source: "felt+airtable" },
  { id: "3b60f454", name: "Hugging Face", lat: 40.6960721, lng: -73.9864229, area: "brooklyn", stage: "Late-Stage", sector: "AI/Data Infrastructure", office: "HQ", website: "https://huggingface.co/", source: "felt+airtable" },
  { id: "b599bee5", name: "Hume.ai", lat: 40.7383425, lng: -73.986331, area: "flatiron", stage: "Early-Stage", sector: "AI Application", office: "HQ", website: "https://www.hume.ai/", source: "felt+airtable" },
  { id: "19c795fd", name: "Modal", lat: 40.7201832, lng: -73.997414, area: "soho", stage: "Early-Stage", sector: "AI/Data Infrastructure", office: "HQ", website: "https://modal.com", source: "felt+airtable" },
  { id: "3aed3995", name: "Nomic", lat: 40.7338522, lng: -73.988917, area: "flatiron", stage: null, sector: "Mapped startup", office: null, website: null, source: "felt" },
  { id: "90fc53b8", name: "Norm AI", lat: 40.7060838, lng: -74.0110631, area: "fidi", stage: "Early-Stage", sector: "Legal", office: "HQ", website: "https://www.norm.ai/", source: "felt+airtable" },
  { id: "openrouter", name: "OpenRouter", lat: 40.747166, lng: -73.98327, area: "midtown", stage: "Late-Stage", sector: "AI/Data Infrastructure", office: "HQ", website: "https://openrouter.ai/", source: "company", address: "169 Madison Avenue, New York, NY 10016" },
  { id: "5775e245", name: "osmo.ai", lat: 40.7364459, lng: -73.989878, area: "flatiron", stage: "Early-Stage", sector: "AI Application", office: "HQ", website: "https://www.osmo.ai/", source: "felt+airtable" },
  { id: "a9d9b894", name: "Patronus.ai", lat: 40.7301567, lng: -73.9877532, area: "flatiron", stage: "Early-Stage", sector: "DevOps", office: "HQ", website: "https://www.patronus.ai/", source: "felt+airtable" },
  { id: "9d2f04ad", name: "Pinecone", lat: 40.7477441, lng: -73.988356, area: "midtown", stage: "Late-Stage", sector: "AI/Data Infrastructure", office: "HQ", website: "https://www.pinecone.io/", source: "felt+airtable" },
  { id: "bbf65c57", name: "PromptLayer", lat: 40.731321, lng: -73.9935622, area: "flatiron", stage: "Early-Stage", sector: "AI/Data Infrastructure", office: "HQ", website: "https://promptlayer.com/", source: "felt+airtable" },
  { id: "ramp", name: "Ramp", lat: 40.7419332, lng: -73.9908991, area: "flatiron", stage: "Late-Stage", sector: "Financial Services", office: "HQ", website: "https://ramp.com/", source: "company", address: "28 West 23rd Street, New York, NY 10010" },
  { id: "4159bd84", name: "Replit", lat: 40.6950298, lng: -73.9739871, area: "brooklyn", stage: "Late-Stage", sector: "AI/Data Infrastructure", office: "Satellite Office", website: "https://replit.com/", source: "felt+airtable" },
  { id: "2d741b46", name: "Rogo", lat: 40.7532487, lng: -73.9787363, area: "midtown", stage: "Early-Stage", sector: "Financial Services", office: "HQ", website: "https://www.rogodata.com/", source: "felt+airtable" },
  { id: "a9e416ad", name: "Runhouse", lat: 40.7330241, lng: -73.988779, area: "flatiron", stage: "Early-Stage", sector: "AI/Data Infrastructure", office: "HQ", website: "https://www.run.house/", source: "felt+airtable" },
  { id: "66afbf68", name: "Runway", lat: 40.7341292, lng: -73.992965, area: "flatiron", stage: "Late-Stage", sector: "Media/Creative", office: "HQ", website: "https://runwayml.com/", source: "felt+airtable" },
  { id: "eabcc144", name: "Sandbar", lat: 40.7417379, lng: -74.008057, area: "west-side", stage: "Early-Stage", sector: "AI Interface", office: "HQ", website: "https://sandbar.inc/", source: "felt+airtable" },
  { id: "1e5b0cb0", name: "Seek AI", lat: 40.7204872, lng: -74.00454, area: "soho", stage: "Early-Stage", sector: "Enterprise Automation", office: "HQ", website: "https://www.seek.ai/", source: "felt+airtable" },
  { id: "b9767786", name: "Slingshot.ai", lat: 40.7340474, lng: -73.9899434, area: "flatiron", stage: "Early-Stage", sector: "Healthcare", office: "HQ", website: "https://www.slingshot.xyz/", source: "felt+airtable" },
  { id: "3cb319a2", name: "Snowflake", lat: 40.7501343, lng: -73.986113, area: "midtown", stage: "Public", sector: "AI/Data Infrastructure", office: "Satellite Office", website: "https://www.snowflake.com/en/", source: "felt+airtable" },
  { id: "e25f0e91", name: "Stainless API", lat: 40.6960712, lng: -73.983292, area: "brooklyn", stage: "Early-Stage", sector: "AI/Data Infrastructure", office: "HQ", website: "https://www.stainlessapi.com", source: "felt+airtable" },
  { id: "c3a4e9d6", name: "Summer Health", lat: 40.7386876, lng: -73.9889957, area: "flatiron", stage: "Early-Stage", sector: "Healthcare", office: "HQ", website: "https://summerhealth.com/", source: "felt+airtable" },
  { id: "d05707e8", name: "Tennr", lat: 40.7297238, lng: -73.9900514, area: "flatiron", stage: "Early-Stage", sector: "Healthcare", office: "HQ", website: "https://www.tennr.com/", source: "felt+airtable" },
  { id: "together-ai", name: "Together AI", lat: 40.754588212187, lng: -73.971575291769, area: "midtown", stage: "Late-Stage", sector: "AI/Data Infrastructure", office: "Satellite Office", website: "https://www.together.ai/", source: "user", address: "777 3RD AVE, NEW YORK, NY, 10017" },
  { id: "vast-data", name: "VAST Data", lat: 40.7534246, lng: -73.9910433, area: "midtown", stage: "Late-Stage", sector: "AI/Data Infrastructure", office: null, website: "https://www.vastdata.com/", source: "company", address: "240 West 37th Street, New York, NY 10018" },
  { id: "f6c37c10", name: "Vic.ai", lat: 40.7553967, lng: -73.97223, area: "midtown", stage: "Early-Stage", sector: "Financial Services", office: "HQ", website: "https://www.vic.ai/", source: "felt+airtable" },
  { id: "ee75072a", name: "Wiz", lat: 40.7479997, lng: -73.9977045, area: "midtown", stage: "Late-Stage", sector: "Security", office: "HQ", website: "https://www.wiz.io/", source: "felt+airtable" },
];

// Short, human-written summaries + an approximate location (street · neighborhood,
// never the exact unit). Keyed by startup id.
export const COMPANY_INFO = {
  "65a0d5fc": { blurb: "AI-native security that stops socially-engineered email and account-takeover attacks.", loc: "Union Square" },
  d5a8e3da: { blurb: "Automates healthcare revenue cycle and medical billing with AI.", loc: "Wall St · FiDi" },
  alphasense: { blurb: "AI-powered market intelligence for financial and business research.", loc: "9th Ave · Hudson Yards" },
  "01d9c120": { blurb: "AI agents that optimize pricing and operations for industrial enterprises.", loc: "E 15th St · Union Square" },
  "24a8d04f": { blurb: "AI quality engineering that catches manufacturing defects before they ship.", loc: "Grand St · Williamsburg" },
  "02910734": { blurb: "Autonomous AI agents that do real accounting work alongside finance teams.", loc: "E 18th St · Flatiron" },
  "55265691": { blurb: "AI-powered video creation and editing studio built for creators.", loc: "E 9th St · Greenwich Village" },
  aea536d9: { blurb: "Consumer app for chatting with millions of user-made AI characters.", loc: "E 9th St · Greenwich Village" },
  df0ea37f: { blurb: "Builder of Devin, the autonomous AI software engineer.", loc: "E 13th St · Greenwich Village" },
  "69020f2f": { blurb: "Enterprise LLMs and retrieval for secure, private business AI.", loc: "Bethune St · West Village" },
  "7b24b80e": { blurb: "AI that clears enterprise and government compliance paperwork.", loc: "Pearl St · FiDi" },
  crosby: { blurb: "An AI-powered law firm automating contract review and negotiation for startups.", loc: "Crosby St · SoHo" },
  dataiku: { blurb: "Enterprise platform for building, deploying, and governing AI systems.", loc: "Broadway · Flatiron" },
  dataminr: { blurb: "AI that detects emerging events and risks from public data in real time.", loc: "E 32nd St · Midtown South" },
  f0167ce8: { blurb: "AI copilot for designing electronics and printed circuit boards.", loc: "Brooklyn Navy Yard" },
  ea7b3bc6: { blurb: "AI automation for back-office and operations workflows.", loc: "William St · FiDi" },
  "4c1746d2": { blurb: "Lifelike AI voice synthesis and text-to-speech in any language.", loc: "Madison Ave · Murray Hill" },
  eliseai: { blurb: "AI agents that automate operations for housing and healthcare providers.", loc: "5th Ave · Midtown" },
  a7dc7d0e: { blurb: "AI financial analyst that automates equity research workflows.", loc: "West Broadway · SoHo" },
  "4fcaccfb": { blurb: "Build and remix small AI apps and image-generation workflows.", loc: "E 42nd St · Midtown" },
  "3789f8f2": { blurb: "AI that reads and answers questions across huge document sets.", loc: "Broadway · SoHo" },
  "3b60f454": { blurb: "The open-source hub for AI models, datasets, and demos.", loc: "Downtown Brooklyn" },
  b599bee5: { blurb: "Emotionally intelligent voice AI grounded in expression science.", loc: "Gramercy Park" },
  "19c795fd": { blurb: "Serverless cloud for running AI, ML, and data workloads.", loc: "Centre Market Pl · Nolita" },
  "3aed3995": { blurb: "Tools to explore, visualize, and structure massive AI datasets.", loc: "E 14th St · Union Square" },
  "90fc53b8": { blurb: "AI agents that automate regulatory compliance.", loc: "Broad St · FiDi" },
  openrouter: { blurb: "A unified API and routing layer for hundreds of AI models.", loc: "Madison Ave · Midtown South" },
  "5775e245": { blurb: "Giving computers a sense of smell by digitizing scent.", loc: "Union Sq West · Union Square" },
  a9d9b894: { blurb: "Automated evaluation and guardrails for large language models.", loc: "E 10th St · Greenwich Village" },
  "9d2f04ad": { blurb: "The vector database powering AI search and retrieval.", loc: "34th St · Midtown" },
  bbf65c57: { blurb: "Prompt management and observability for teams building on LLMs.", loc: "E 8th St · Greenwich Village" },
  ramp: { blurb: "AI-powered corporate cards, expense management, and finance operations.", loc: "W 23rd St · Flatiron" },
  "4159bd84": { blurb: "Browser-based coding platform with an AI software agent.", loc: "Fort Greene · Brooklyn" },
  "2d741b46": { blurb: "AI analyst platform for investment banking and finance.", loc: "One Vanderbilt · Midtown" },
  a9e416ad: { blurb: "Infrastructure to run ML workloads across any cloud or compute.", loc: "E 13th St · Greenwich Village" },
  "66afbf68": { blurb: "Generative AI for video, visual effects, and filmmaking.", loc: "E 12th St · Greenwich Village" },
  eabcc144: { blurb: "Building new AI-native interfaces and devices.", loc: "Little W 12th St · Meatpacking" },
  "1e5b0cb0": { blurb: "Ask data questions in plain English across the enterprise.", loc: "Lispenard St · Tribeca" },
  b9767786: { blurb: "AI for accessible mental and behavioral health support.", loc: "4th Ave · Union Square" },
  "3cb319a2": { blurb: "Cloud data platform and warehouse for AI workloads.", loc: "W 35th St · Midtown" },
  e25f0e91: { blurb: "Generates polished, type-safe SDKs from any API spec.", loc: "Brooklyn Navy Yard" },
  c3a4e9d6: { blurb: "Pediatric telehealth with AI-assisted visit notes.", loc: "E 20th St · Flatiron" },
  d05707e8: { blurb: "AI that automates healthcare referrals and patient intake.", loc: "Astor Pl · NoHo" },
  "together-ai": { blurb: "Cloud platform to train, fine-tune, and run open-source AI models.", loc: "3rd Ave · Midtown East" },
  "vast-data": { blurb: "Data and compute infrastructure for training and running AI at scale.", loc: "W 37th St · Garment District" },
  f6c37c10: { blurb: "Autonomous accounting and accounts-payable automation.", loc: "E 49th St · Midtown East" },
  ee75072a: { blurb: "Cloud security platform that finds and fixes risk across the stack.", loc: "W 26th St · Chelsea" },
};

export const CONTEXT_POINTS = [
  { id: "4d7ccbee", name: "AWS", category: "Big Tech", lat: 40.749712, lng: -73.986496 },
  { id: "a09721fd", name: "Bloomberg", category: "Big Tech", lat: 40.7617428, lng: -73.9678704 },
  { id: "98c10849", name: "Databricks (MosaicML)", category: "Big Tech", lat: 40.7549057, lng: -73.9823909 },
  { id: "0db9c823", name: "Figma", category: "Big Tech", lat: 40.7429387, lng: -73.9901206 },
  { id: "36332df7", name: "Google Chelsea", category: "Big Tech", lat: 40.741616, lng: -74.003906 },
  { id: "838fb95f", name: "Google Houston", category: "Big Tech", lat: 40.7286612, lng: -74.0082998 },
  { id: "65417ef8", name: "Meta", category: "Big Tech", lat: 40.7302556, lng: -73.9917522 },
  { id: "1258f6b5", name: "Meta AI", category: "Big Tech", lat: 40.7506415, lng: -73.9936575 },
  { id: "9ace795f", name: "Microsoft", category: "Big Tech", lat: 40.756764, lng: -73.989858 },
  { id: "4d7e2d55", name: "Notion", category: "Big Tech", lat: 40.723285, lng: -74.006421 },
  { id: "8410c87b", name: "Palantir", category: "Big Tech", lat: 40.7441291, lng: -74.0067573 },
  { id: "fd6541d1", name: "Retool", category: "Big Tech", lat: 40.7398114, lng: -73.9900222 },
  { id: "44e7ae3b", name: "Squarespace", category: "Big Tech", lat: 40.729222, lng: -74.005731 },
  { id: "2bc7ea4c", name: "Stripe", category: "Big Tech", lat: 40.707179, lng: -74.004586 },
  { id: "27dc2e95", name: "Uber", category: "Big Tech", lat: 40.7113558, lng: -74.0120812 },
  { id: "c2d538d7", name: "Verci", category: "Coworking", lat: 40.718305, lng: -74.002316 },
  { id: "17c4013b", name: "WeWork FiDi", category: "Coworking", lat: 40.711359, lng: -74.0086065 },
  { id: "8fe130c2", name: "WeWork Irving Place", category: "Coworking", lat: 40.735098, lng: -73.988293 },
  { id: "cd3ac3bd", name: "WeWork SoHo", category: "Coworking", lat: 40.7238093, lng: -73.9999845 },
  { id: "7e1e122b", name: "AlQuraishi Lab Columbia", category: "Higher Education", lat: 40.8086, lng: -73.9618 },
  { id: "0a44e57f", name: "Columbia University", category: "Higher Education", lat: 40.8074771, lng: -73.9624001 },
  { id: "5f9c066b", name: "Cornell Tech", category: "Higher Education", lat: 40.7558, lng: -73.9525 },
  { id: "d3bc7158", name: "NYU CILVR", category: "Higher Education", lat: 40.730396, lng: -73.995986 },
  { id: "c2ac6f0c", name: "Betaworks", category: "VCs / Events", lat: 40.740323, lng: -74.007694 },
  { id: "1731cccf", name: "Lux Capital", category: "VCs / Events", lat: 40.739565, lng: -73.989416 },
  { id: "ec8f8c29", name: "South Park Commons", category: "VCs / Events", lat: 40.728298, lng: -73.99152 },
  { id: "43836127", name: "Thrive Capital", category: "VCs / Events", lat: 40.724717, lng: -73.995547 },
  { id: "a843ef04", name: "Union Square Ventures", category: "VCs / Events", lat: 40.732709, lng: -73.9904137 },
  { id: "3dfd9247", name: "Work-Bench", category: "VCs / Events", lat: 40.7395005, lng: -73.9899694 },
];
