export const DATA_SOURCES = {
  note: "深圳科技地图。公司坐标为近似值（GCJ-02），基于公开总部地址及科技园区位置，覆盖南山、福田、前海、坂田和宝安。",
};

export const AREAS = [
  {
    id: "all",
    number: "01",
    label: "全局概览",
    shortLabel: "全局",
    focus: { lat: 22.555, lng: 113.975, distance: 98, height: 70, rotation: 0.6 },
    description:
      "47家科技公司，分布在深圳七大产业片区。通信、电子、机器人、自动驾驶、芯片与AI基础设施，按街区精绘于南山、福田、前海、坂田和宝安。",
  },
  {
    id: "nanshan-tech",
    number: "02",
    label: "南山科技园",
    shortLabel: "南山",
    focus: { lat: 22.530, lng: 113.955, distance: 36, height: 30, rotation: 0.5 },
    description:
      "地图上最密集的科技集群。中兴、迈瑞、传音、商汤和速腾聚创沿粤海街道科苑—深南一线分布，覆盖通信、医疗、消费电子与AI全产业链。",
  },
  {
    id: "houhai",
    number: "03",
    label: "后海",
    shortLabel: "后海",
    focus: { lat: 22.510, lng: 113.996, distance: 28, height: 24, rotation: 0.72 },
    description:
      "总部滨水区。腾讯、微众银行和华润春笋共享填海造地的深圳湾新岸线，矗立着城市最高的新建楼宇。",
  },
  {
    id: "qianhai",
    number: "04",
    label: "前海",
    shortLabel: "前海",
    focus: { lat: 22.535, lng: 113.875, distance: 32, height: 26, rotation: 0.92 },
    description:
      "自贸区填海地带。大铲湾腾讯企鹅岛全球总部矗立珠江畔，深港科技与金融企业在此扎根。",
  },
  {
    id: "futian",
    number: "05",
    label: "福田",
    shortLabel: "福田",
    focus: { lat: 22.538, lng: 114.060, distance: 32, height: 28, rotation: 0.42 },
    description:
      "金融核心区。平安、顺丰、荣耀和汇顶在599米高的平安金融中心之下，布局金融科技、物流与消费电子。",
  },
  {
    id: "liuxiandong",
    number: "06",
    label: "留仙洞",
    shortLabel: "留仙洞",
    focus: { lat: 22.578, lng: 113.945, distance: 30, height: 25, rotation: 0.6 },
    description:
      "机器人之岭。大疆天空之城、优必选、越疆和深信服沿西丽山麓分布，是深圳硬件基因与机器人产业的聚集地。",
  },
  {
    id: "longgang",
    number: "07",
    label: "坂田",
    shortLabel: "坂田",
    focus: { lat: 22.642, lng: 114.060, distance: 34, height: 28, rotation: 0.35 },
    description:
      "通信与电子制造核心。华为坂田全球总部和工业富联龙华基地，撑起深圳最重的科技产业链。",
  },
  {
    id: "baoan",
    number: "08",
    label: "宝安",
    shortLabel: "宝安",
    focus: { lat: 22.545, lng: 113.855, distance: 34, height: 27, rotation: 1.0 },
    description:
      "西部制造带。大族激光、欣旺达和智能装备企业沿107国道分布，为深圳硬件供应链提供支撑。",
  },
];

// Company records keyed by id. Coordinates are approximate (GCJ-02), anchored to
// public HQ addresses and tech-park locations — never an exact office unit.
export const STARTUPS = [
  { id: "autox", name: "AutoX", nameZh: "安途", lat: 22.5600, lng: 113.9150, area: "nanshan-tech", stage: "后期", sector: "自动驾驶", office: "总部", website: "https://www.autox.ai/", source: "user" },
  { id: "corerain", name: "Corerain", nameZh: "鲲云科技", lat: 22.5300, lng: 114.0560, area: "futian", stage: "早期", sector: "AI芯片", office: "总部", website: "https://www.corerain.com/", source: "user" },
  { id: "deeproute", name: "DeepRoute.ai", nameZh: "元戎启行", lat: 22.5200, lng: 113.9600, area: "nanshan-tech", stage: "早期", sector: "AI应用", office: "总部", website: "https://www.deeproute.ai/", source: "user" },
  { id: "dji", name: "DJI", nameZh: "大疆创新", lat: 22.5775, lng: 113.9429, area: "liuxiandong", stage: "后期", sector: "制造与工业", office: "总部", website: "https://www.dji.com/", source: "company" },
  { id: "dji-automotive", name: "DJI Automotive", nameZh: "大疆车载", lat: 22.5750, lng: 113.9450, area: "liuxiandong", stage: "早期", sector: "AI应用", office: "总部", website: "https://auto.dji.com/", source: "user" },
  { id: "dobot", name: "Dobot", nameZh: "越疆科技", lat: 22.5850, lng: 113.9550, area: "liuxiandong", stage: "上市", sector: "制造与工业", office: "总部", website: "https://www.dobot.cc/", source: "user" },
  { id: "flexium", name: "Flexium", nameZh: "鹏鼎控股", lat: 22.5400, lng: 113.9370, area: "nanshan-tech", stage: "上市", sector: "电子制造", office: "总部", website: "https://www.flexium.com.tw/", source: "user" },
  { id: "foxconn", name: "Foxconn", nameZh: "工业富联", lat: 22.6400, lng: 114.0800, area: "longgang", stage: "上市", sector: "电子制造", office: "总部", website: "https://www.foxconn.com/", source: "user" },
  { id: "goodix", name: "Goodix", nameZh: "汇顶科技", lat: 22.5710, lng: 114.0600, area: "futian", stage: "上市", sector: "AI芯片", office: "总部", website: "https://www.goodix.com/", source: "user" },
  { id: "hai-robotics", name: "HAI Robotics", nameZh: "海柔创新", lat: 22.5350, lng: 113.9650, area: "nanshan-tech", stage: "后期", sector: "企业自动化", office: "总部", website: "https://www.hairobotics.com/", source: "user" },
  { id: "hans-laser", name: "Han's Laser", nameZh: "大族激光", lat: 22.6100, lng: 113.8500, area: "baoan", stage: "上市", sector: "制造与工业", office: "总部", website: "https://www.hanslaser.com/", source: "user" },
  { id: "honor", name: "Honor", nameZh: "荣耀", lat: 22.5400, lng: 114.0800, area: "futian", stage: "后期", sector: "消费电子", office: "总部", website: "https://www.hihonor.com/", source: "user" },
  { id: "huawei", name: "Huawei", nameZh: "华为", lat: 22.6430, lng: 114.0530, area: "longgang", stage: "上市", sector: "通信设备", office: "总部", website: "https://www.huawei.com/", source: "company" },
  { id: "icarbonx", name: "iCarbonX", nameZh: "碳云智能", lat: 22.5200, lng: 113.9650, area: "nanshan-tech", stage: "后期", sector: "医疗健康", office: "总部", website: "https://www.icarbonx.com/", source: "user" },
  { id: "intellifusion", name: "Intellifusion", nameZh: "云天励飞", lat: 22.5400, lng: 113.9450, area: "nanshan-tech", stage: "上市", sector: "AI应用", office: "总部", website: "https://www.intellifusion.com/", source: "user" },
  { id: "kingdee", name: "Kingdee", nameZh: "金蝶", lat: 22.5360, lng: 113.9370, area: "nanshan-tech", stage: "上市", sector: "企业数智", office: "总部", website: "https://www.kingdee.com/", source: "user" },
  { id: "leadshine", name: "Leadshine", nameZh: "雷赛智能", lat: 22.5450, lng: 113.9500, area: "nanshan-tech", stage: "上市", sector: "制造与工业", office: "总部", website: "https://www.leadshine.com/", source: "user" },
  { id: "leju", name: "Leju Robot", nameZh: "乐聚机器人", lat: 22.5900, lng: 113.9500, area: "liuxiandong", stage: "早期", sector: "制造与工业", office: "总部", website: "https://www.lejurobotics.com/", source: "user" },
  { id: "limx", name: "LimX Dynamics", nameZh: "逐际动力", lat: 22.5850, lng: 113.9600, area: "liuxiandong", stage: "早期", sector: "制造与工业", office: "总部", website: "https://www.limxdynamics.com/", source: "user" },
  { id: "linklogis", name: "Linklogis", nameZh: "联易融", lat: 22.5310, lng: 113.8970, area: "qianhai", stage: "上市", sector: "供应链金融", office: "总部", website: "https://www.linklogis.com/", source: "user" },
  { id: "mindray", name: "Mindray", nameZh: "迈瑞医疗", lat: 22.5380, lng: 113.9370, area: "nanshan-tech", stage: "上市", sector: "医疗AI", office: "总部", website: "https://www.mindray.com/", source: "user" },
  { id: "moffett", name: "Moffett AI", nameZh: "墨芯人工智能", lat: 22.5300, lng: 113.8950, area: "qianhai", stage: "早期", sector: "AI芯片", office: "总部", website: "http://moffettai.com/", source: "user" },
  { id: "narwal", name: "Narwal", nameZh: "云鲸智能", lat: 22.5850, lng: 113.9500, area: "liuxiandong", stage: "后期", sector: "家用机器人", office: "总部", website: "https://narwal.com/", source: "user" },
  { id: "orbbec", name: "Orbbec", nameZh: "奥比中光", lat: 22.5200, lng: 113.9700, area: "nanshan-tech", stage: "上市", sector: "AI/数据基础设施", office: "总部", website: "https://www.orbbec.com/", source: "user" },
  { id: "pingan-tech", name: "PingAn Tech", nameZh: "平安科技", lat: 22.5332, lng: 114.0556, area: "futian", stage: "上市", sector: "金融服务", office: "总部", website: "https://www.pingan.com/", source: "company" },
  { id: "pudu", name: "Pudu Robotics", nameZh: "普渡科技", lat: 22.5800, lng: 113.9550, area: "liuxiandong", stage: "后期", sector: "服务机器人", office: "总部", website: "https://www.pudutech.com/", source: "user" },
  { id: "robosense", name: "RoboSense", nameZh: "速腾聚创", lat: 22.5400, lng: 113.9600, area: "nanshan-tech", stage: "上市", sector: "AI/数据基础设施", office: "总部", website: "https://www.robosense.ai/", source: "user" },
  { id: "sangfor", name: "Sangfor", nameZh: "深信服", lat: 22.5790, lng: 113.9470, area: "liuxiandong", stage: "上市", sector: "AI安全", office: "总部", website: "https://www.sangfor.com/", source: "user" },
  { id: "sensetime-sz", name: "SenseTime (SZ)", nameZh: "商汤科技", lat: 22.5200, lng: 113.9650, area: "nanshan-tech", stage: "上市", sector: "AI应用", office: "分支机构", website: "https://www.sensetime.com/", source: "user" },
  { id: "sf-express", name: "SF Express", nameZh: "顺丰速运", lat: 22.5400, lng: 114.0600, area: "futian", stage: "上市", sector: "物流科技", office: "总部", website: "https://www.sf-express.com/", source: "company" },
  { id: "sf-tech", name: "SF Technology", nameZh: "顺丰科技", lat: 22.5400, lng: 114.0600, area: "futian", stage: "后期", sector: "企业自动化", office: "总部", website: "https://www.sf-tech.com.cn/", source: "user" },
  { id: "smartmore", name: "SmartMore", nameZh: "思谋科技", lat: 22.5350, lng: 113.9500, area: "nanshan-tech", stage: "早期", sector: "AI应用", office: "总部", website: "https://www.smartmore.com/", source: "user" },
  { id: "speakin", name: "SpeakIn", nameZh: "声扬科技", lat: 22.5400, lng: 113.9500, area: "nanshan-tech", stage: "早期", sector: "语音AI", office: "总部", website: "https://www.speakin.ai/", source: "user" },
  { id: "standard-robots", name: "Standard Robots", nameZh: "斯坦德机器人", lat: 22.5550, lng: 113.9600, area: "nanshan-tech", stage: "早期", sector: "工业AMR", office: "总部", website: "https://www.standard-robots.com/", source: "user" },
  { id: "stardust", name: "Stardust AI", nameZh: "星尘智能", lat: 22.5250, lng: 113.9580, area: "nanshan-tech", stage: "早期", sector: "具身智能", office: "总部", website: "https://www.astribot.com/", source: "user" },
  { id: "sunline", name: "Sunline", nameZh: "长亮科技", lat: 22.5250, lng: 113.9520, area: "nanshan-tech", stage: "上市", sector: "金融科技", office: "总部", website: "https://www.sunline.cn/", source: "user" },
  { id: "sunwoda", name: "Sunwoda", nameZh: "欣旺达", lat: 22.5600, lng: 113.8900, area: "baoan", stage: "上市", sector: "新能源", office: "总部", website: "https://www.sunwoda.com/", source: "user" },
  { id: "tencent", name: "Tencent", nameZh: "腾讯", lat: 22.5228, lng: 113.9353, area: "houhai", stage: "上市", sector: "互联网平台", office: "总部", website: "https://www.tencent.com/", source: "company" },
  { id: "topband", name: "Topband", nameZh: "拓邦股份", lat: 22.5550, lng: 113.9400, area: "nanshan-tech", stage: "上市", sector: "智能控制", office: "总部", website: "http://tuobanggufen.com.cn/", source: "user" },
  { id: "transsion", name: "Transsion", nameZh: "传音控股", lat: 22.5470, lng: 113.9350, area: "nanshan-tech", stage: "上市", sector: "消费电子", office: "总部", website: "https://www.transsion.com/", source: "user" },
  { id: "ubtech", name: "UBTech", nameZh: "优必选", lat: 22.5960, lng: 113.9480, area: "liuxiandong", stage: "上市", sector: "制造与工业", office: "总部", website: "https://www.ubtrobot.com/", source: "user" },
  { id: "webank", name: "WeBank", nameZh: "微众银行", lat: 22.5220, lng: 113.9380, area: "houhai", stage: "后期", sector: "金融服务", office: "总部", website: "https://www.webank.com/", source: "user" },
  { id: "wondershare", name: "Wondershare", nameZh: "万兴科技", lat: 22.5350, lng: 113.9550, area: "nanshan-tech", stage: "上市", sector: "媒体/创意", office: "总部", website: "https://www.wondershare.com/", source: "user" },
  { id: "xverse", name: "XVERSE", nameZh: "元象万物", lat: 22.5300, lng: 113.9580, area: "nanshan-tech", stage: "早期", sector: "AI应用", office: "总部", website: "https://www.xverse.cn/", source: "user" },
  { id: "xtalpi", name: "XtalPi", nameZh: "晶泰科技", lat: 22.5250, lng: 113.9550, area: "nanshan-tech", stage: "后期", sector: "医疗健康", office: "总部", website: "https://www.xtalpi.com/", source: "user" },
  { id: "zhuiyi", name: "Zhuiyi", nameZh: "追一科技", lat: 22.5550, lng: 113.9400, area: "nanshan-tech", stage: "早期", sector: "企业自动化", office: "总部", website: "https://www.zhuiyi.ai/", source: "user" },
  { id: "zte", name: "ZTE", nameZh: "中兴通讯", lat: 22.5380, lng: 113.9420, area: "nanshan-tech", stage: "上市", sector: "通信设备", office: "总部", website: "https://www.zte.com.cn/", source: "user" },
];

// Short, human-written summaries + an approximate location (street · district,
// never the exact unit). Keyed by startup id.
export const COMPANY_INFO = {
  autox: { blurb: "L4级无人驾驶RoboTaxi，在中美多城开展全无人运营。", loc: "北环大道 · 南山" },
  corerain: { blurb: "基于CAISA架构的国产AI加速芯片，高性能推理。", loc: "市花路 · 福田保税区" },
  deeproute: { blurb: "深圳本土L4自动驾驶公司，聚焦Robotaxi和货运。", loc: "科苑路 · 南山" },
  dji: { blurb: "全球消费级和行业级无人机领军企业。", loc: "仙元路 · 留仙洞" },
  "dji-automotive": { blurb: "大疆旗下独立运营的智能驾驶全场景解决方案提供商。", loc: "仙元路 · 留仙洞" },
  dobot: { blurb: "桌面及工业协作机器人，产品销往全球。", loc: "学苑大道 · 西丽" },
  flexium: { blurb: "柔性线路板(FPC)龙头，消费电子核心供应链。", loc: "科技南十二路 · 南山" },
  foxconn: { blurb: "全球最大电子制造服务商，通信/消费电子代工龙头。", loc: "东环二路 · 龙华" },
  goodix: { blurb: "生物识别传感芯片，指纹/触控/音频/安全全栈。", loc: "梅康路 · 福田" },
  "hai-robotics": { blurb: "箱式仓储机器人，开创自主箱式搬运技术。", loc: "科技路 · 南山" },
  "hans-laser": { blurb: "工业激光及智能制造装备。", loc: "107国道 · 宝安" },
  honor: { blurb: "智能手机品牌，独立后扎根深圳，拓展IoT生态。", loc: "上梅林 · 福田" },
  huawei: { blurb: "全球通信与ICT龙头，5G/芯片/终端/云计算全栈。", loc: "坂田基地 · 龙岗" },
  icarbonx: { blurb: "数字生命平台，融合AI与多组学健康数据。", loc: "科技路 · 南山" },
  intellifusion: { blurb: "算法+芯片+数据全栈AI，服务于数字城市和安防。", loc: "科技路 · 南山" },
  kingdee: { blurb: "企业级ERP与云服务，苍穹PaaS平台引领数字化。", loc: "科技南十二路 · 南山" },
  leadshine: { blurb: "运动控制与伺服驱动，驱动机器人与自动化设备。", loc: "南山大道 · 南山" },
  leju: { blurb: "人形及双足机器人，夸父平台研发者。", loc: "学苑大道 · 西丽" },
  limx: { blurb: "人形及足式机器人，具备高力矩运动控制能力。", loc: "机器人谷 · 西丽" },
  linklogis: { blurb: "供应链金融科技SaaS，腾讯系供应链金融生态。", loc: "前海周大福大厦 · 前海" },
  mindray: { blurb: "全球医疗器械龙头，生命信息、体外诊断与医学影像。", loc: "科技南十二路 · 南山" },
  moffett: { blurb: "稀疏计算AI芯片，突破性高算力低功耗推理。", loc: "弘毅大厦 · 前海" },
  narwal: { blurb: "智能扫地机器人与洗地机，自清洁方案开创者。", loc: "万科云城 · 西丽" },
  orbbec: { blurb: "3D视觉传感芯片和相机，面向消费和工业场景。", loc: "高新南环路 · 南山" },
  "pingan-tech": { blurb: "面向金融、保险和医疗的AI、云和区块链技术。", loc: "益田路 · 福田" },
  pudu: { blurb: "全球服务机器人领导品牌，累计出货超12万台。", loc: "国际创新谷 · 西丽" },
  robosense: { blurb: "面向自动驾驶的固态和机械式激光雷达。", loc: "科技路 · 南山" },
  sangfor: { blurb: "AI驱动的网络安全与云计算，零信任架构。", loc: "仙洞路 · 西丽" },
  "sensetime-sz": { blurb: "计算机视觉基础模型，赋能智慧城市和智能汽车。", loc: "科技路 · 南山" },
  "sf-express": { blurb: "中国最大综合物流服务商，科技驱动智慧供应链。", loc: "新沙路 · 福田" },
  "sf-tech": { blurb: "驱动顺丰物流的AI与大数据平台。", loc: "新沙路 · 福田" },
  smartmore: { blurb: "面向智能制造和视频的AI视觉架构。", loc: "科技路 · 南山" },
  speakin: { blurb: "声纹识别与语音生物特征认证。", loc: "科技路 · 南山" },
  "standard-robots": { blurb: "工业自主移动机器人(AMR)，3C制造领域头部。", loc: "科苑路 · 南山" },
  stardust: { blurb: "绳驱AI机器人，高性能仿人操作与具身智能。", loc: "深圳湾创新科技中心 · 南山" },
  sunline: { blurb: "银行核心系统龙头，全球金融科技解决方案。", loc: "深圳湾科技生态园 · 南山" },
  sunwoda: { blurb: "锂离子电池模组龙头，消费电子与新能源双轮驱动。", loc: "石岩街道 · 宝安" },
  tencent: { blurb: "社交、云和AI巨头，混元大模型研发者。", loc: "海天二路 · 后海" },
  topband: { blurb: "智能控制器与新能源BMS，万物智联底层。", loc: "朗山路 · 南山" },
  transsion: { blurb: "非洲手机之王，全球新兴市场消费电子龙头。", loc: "深圳湾科技生态园 · 南山" },
  ubtech: { blurb: "人形机器人全栈，Walker S已进入工厂部署。", loc: "学苑大道 · 西丽" },
  webank: { blurb: "国内首家数字银行，AI驱动的小微金融规模化。", loc: "后海大道 · 后海" },
  wondershare: { blurb: "数字创意和生产力软件，集成AI工具。", loc: "科技路 · 南山" },
  xverse: { blurb: "通用大模型与VR大空间交互。", loc: "科技路 · 南山" },
  xtalpi: { blurb: "基于AI和量子物理的药物研发与材料发现。", loc: "科技路 · 南山" },
  zhuiyi: { blurb: "面向服务、营销和运营的AI数字员工。", loc: "科技路 · 南山" },
  zte: { blurb: "5G与通信基础设施，AI原生网络。", loc: "科技路 · 南山" },
};

export const CONTEXT_POINTS = [
  { id: "byd", name: "比亚迪", category: "科技巨头", lat: 22.6900, lng: 114.3300 },
  { id: "pingan-group", name: "平安集团", category: "科技巨头", lat: 22.5332, lng: 114.0556 },
  { id: "cmb", name: "招商银行", category: "科技巨头", lat: 22.5350, lng: 114.0600 },
  { id: "tencent-qd", name: "腾讯企鹅岛", category: "科技巨头", lat: 22.5370, lng: 113.8670 },
  { id: "sustech", name: "南方科技大学", category: "高校院所", lat: 22.6000, lng: 113.9990 },
  { id: "szu", name: "深圳大学", category: "高校院所", lat: 22.5350, lng: 113.9380 },
  { id: "hitsz", name: "哈工大（深圳）", category: "高校院所", lat: 22.5900, lng: 113.9820 },
  { id: "tsinghua-sz", name: "清华深圳国际研究生院", category: "高校院所", lat: 22.6000, lng: 113.9800 },
  { id: "pengcheng-lab", name: "鹏城实验室", category: "高校院所", lat: 22.6020, lng: 113.9700 },
  { id: "szvc", name: "深创投", category: "投资机构", lat: 22.5400, lng: 114.0600 },
  { id: "songhe", name: "松禾资本", category: "投资机构", lat: 22.5350, lng: 113.9500 },
  { id: "greenpine", name: "青松资本", category: "投资机构", lat: 22.5380, lng: 113.9450 },
];
